version: '3.9'

services:
  chroma:
    image: chromadb/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - 8000:8000
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - CHROMA_PERSISTENCE_DIRECTORY=/chroma/chroma
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_HOST=0.0.0.0
      - ANONYMIZED_TELEMETRY=False
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  chroma_data:
    driver: local