global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Scrape Node Exporter for host metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Scrape cAdvisor for container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Milvus metrics
  - job_name: "milvus"
    metrics_path: /metrics
    static_configs:
      - targets: ["milvus-standalone:9091"]
        labels:
          service: "milvus"

  # Qdrant metrics (if exposed)
  - job_name: "qdrant"
    metrics_path: /metrics
    static_configs:
      - targets: ["qdrant:6333"]
        labels:
          service: "qdrant"

  # Weaviate metrics
  - job_name: "weaviate"
    metrics_path: /v1/metrics
    static_configs:
      - targets: ["weaviate:8080"]
        labels:
          service: "weaviate"

  # HTTP endpoint monitoring (for APIs that don't expose metrics)
  - job_name: "http_endpoints"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://chroma:8000/api/v1/heartbeat # Chroma
          - http://faiss-api:5000/health # FAISS API
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
